### PR TITLE
bigdft-suite: add variant to enable-dynamic-libraries

### PR DESCRIPTION
**Pull request by iamashwin99**
bigdft-suite: add variant to enable-dynamic-libraries

### CODE REVIEW

**Comment by fangohr** [comment]
Thank you.

The changes look straigtforward. Can you give some context (or point to the relevant issues):

- why is this needed / which problem does it fix
- is this already or will be proposed upstream?
- is this change (and subsequent Octopus compilation) running in a CI somewhere?

**Comment by iamashwin99** [comment]
This is an attempt to fix the issue at https://gitlab.com/octopus-code/octopus/-/issues/833, as followed in discussion at https://zulip.mpsd.mpg.de/#narrow/stream/4-ssu-cs-internal/topic/toolchains/near/65853.

Here's a summary:
- futile isnt picked up from the spack toolchain when Octopus is configured to build without openmp
- the error message mentions openmp related symbols
- we build it as a static library
- easy build builds both static and shared lib. The build bot configure uses the shared library
- when we build futile as a shared library, the m4 picks up the futile even when openmp is disabled (as reported in the issue)
- we then must build our toolchains with futile and other bigdft libs as a shared lib

This MR adds a default variant of building dynamic libraries (shared libraries) as is typical of other libraries

**Comment by iamashwin99** [comment]
With this mr the toolchain compiled gets the FUTILE detection right:
config.h = https://sprunge.us/5lb8ii
config.log = https://sprunge.us/wSbOmW

**Comment by iamashwin99** [comment]
Moving this MR to reference the `23c` release which is also based on spack v0.19. Based on the discussion today.

**Comment by iamashwin99** [comment]
Made the variant shared the default because the default behaviour of most packages is to build dynamic libraries, and most spack variants that have the `shared` variant also make it default.

**Comment by fangohr** [comment]
Nice, thank you.

@iamashwin99 - can you create a merge request for upstream spack with the same changes? (if this is done already, please add a link here.)

**Comment by iamashwin99** [comment]
I have added them here : https://github.com/spack/spack/pull/41562

**Pull request merged**
